	[TierSettings.BrassTier]
		#Item capability for brass tier mechanical[default:256]
		# Default: 256
		# Range: > 1
		brass_item_capability = 256
		#Fluid capability for brass tier mechanical[default:4000]
		# Default: 4000
		# Range: > 1
		brass_fluid_capability = 4000
		#Fluid Tank capability for brass tier mechanical[default:32000]
		# Default: 32000
		# Range: > 1
		brass_fluid_tank_capability = 32000
		#Processing multiple for brass tier mechanical[default:4]
		# Default: 4
		# Range: > 1
		brass_processing_multiple = 4
		#Processing multiple for brass tier Deployer[default:4]
		# Default: 4
		# Range: 1 ~ 64
		brass_deployer_processing_multiple = 4
		#Generated Speed for brass tier Steam Engine[default:64]
		# Default: 64
		# Range: 1 ~ 256
		brass_steam_engine_generated_speed = 64
		#Capacity for brass tier Steam Engine[default:2048.0]
		# Default: 2048.0
		# Range: 1.0 ~ 2.147483647E9
		brass_steam_engine_capacity = 2048.0
		#Impact needed for brass tier mechanical press[default:32.0]
		# Default: 32.0
		# Range: 1.0 ~ 1.7976931348623157E308
		brass_mechanical_press_impact = 32.0
		#Impact needed for brass tier mechanical mixer[default:16.0]
		# Default: 16.0
		# Range: 1.0 ~ 1.7976931348623157E308
		brass_mechanical_mixer_impact = 16.0
		#Impact needed forbrass tier deployer[default:16.0]
		# Default: 16.0
		# Range: 1.0 ~ 1.7976931348623157E308
		brassdeployer_impact = 16.0
		#Impact needed for brass tier saw[default:8.0]
		# Default: 8.0
		# Range: 1.0 ~ 1.7976931348623157E308
		brass_saw_impact = 8.0
		#Inventory size for brass tier saw[default:64]
		# Default: 64
		# Range: 4 ~ 4096
		brass_saw_inventory_size = 64

	[TierSettings.NetheriteTier]
		#Item capability for netherite tier mechanical[default:1024]
		# Default: 1024
		# Range: > 1
		netherite_item_capability = 1024
		#Fluid capability for netherite tier mechanical[default:16000]
		# Default: 16000
		# Range: > 1
		netherite_fluid_capability = 16000
		#Fluid Tank capability for netherite tier mechanical[default:64000]
		# Default: 64000
		# Range: > 1
		netherite_fluid_tank_capability = 64000
		#Processing multiple for netherite tier mechanical[default:16]
		# Default: 16
		# Range: > 1
		netherite_processing_multiple = 16
		#Processing multiple for netherite tier Deployer[default:8]
		# Default: 8
		# Range: 1 ~ 64
		netherite_deployer_processing_multiple = 8
		#Generated Speed for netherite tier Steam Engine[default:64]
		# Default: 64
		# Range: 1 ~ 256
		netherite_steam_engine_generated_speed = 64
		#Capacity for netherite tier Steam Engine[default:4096.0]
		# Default: 4096.0
		# Range: 1.0 ~ 2.147483647E9
		netherite_steam_engine_capacity = 4096.0
		#Impact needed for netherite tier mechanical press[default:128.0]
		# Default: 128.0
		# Range: 1.0 ~ 1.7976931348623157E308
		netherite_mechanical_press_impact = 128.0
		#Impact needed for netherite tier mechanical mixer[default:64.0]
		# Default: 64.0
		# Range: 1.0 ~ 1.7976931348623157E308
		netherite_mechanical_mixer_impact = 64.0
		#Impact needed fornetherite tier deployer[default:32.0]
		# Default: 32.0
		# Range: 1.0 ~ 1.7976931348623157E308
		netheritedeployer_impact = 32.0
		#Impact needed for netherite tier saw[default:32.0]
		# Default: 32.0
		# Range: 1.0 ~ 1.7976931348623157E308
		netherite_saw_impact = 32.0
		#Inventory size for netherite tier saw[default:128]
		# Default: 128
		# Range: 4 ~ 4096
		netherite_saw_inventory_size = 128

	[TierSettings.EndTier]
		#Item capability for end tier mechanical[default:4096]
		# Default: 4096
		# Range: > 1
		end_item_capability = 4096
		#Fluid capability for end tier mechanical[default:64000]
		# Default: 64000
		# Range: > 1
		end_fluid_capability = 64000
		#Fluid Tank capability for end tier mechanical[default:256000]
		# Default: 256000
		# Range: > 1
		end_fluid_tank_capability = 256000
		#Processing multiple for end tier mechanical[default:64]
		# Default: 64
		# Range: > 1
		end_processing_multiple = 64
		#Processing multiple for end tier Deployer[default:16]
		# Default: 16
		# Range: 1 ~ 64
		end_deployer_processing_multiple = 16
		#Generated Speed for end tier Steam Engine[default:128]
		# Default: 128
		# Range: 1 ~ 256
		end_steam_engine_generated_speed = 128
		#Capacity for end tier Steam Engine[default:8192.0]
		# Default: 8192.0
		# Range: 1.0 ~ 2.147483647E9
		end_steam_engine_capacity = 8192.0
		#Impact needed for end tier mechanical press[default:512.0]
		# Default: 512.0
		# Range: 1.0 ~ 1.7976931348623157E308
		end_mechanical_press_impact = 512.0
		#Impact needed for end tier mechanical mixer[default:256.0]
		# Default: 256.0
		# Range: 1.0 ~ 1.7976931348623157E308
		end_mechanical_mixer_impact = 256.0
		#Impact needed forend tier deployer[default:64.0]
		# Default: 64.0
		# Range: 1.0 ~ 1.7976931348623157E308
		enddeployer_impact = 64.0
		#Impact needed for end tier saw[default:128.0]
		# Default: 128.0
		# Range: 1.0 ~ 1.7976931348623157E308
		end_saw_impact = 128.0
		#Inventory size for end tier saw[default:256]
		# Default: 256
		# Range: 4 ~ 4096
		end_saw_inventory_size = 256

	[TierSettings.BeyondTier]
		#Item capability for beyond tier mechanical[default:16384]
		# Default: 16384
		# Range: > 1
		beyond_item_capability = 16384
		#Fluid capability for beyond tier mechanical[default:256000]
		# Default: 256000
		# Range: > 1
		beyond_fluid_capability = 256000
		#Fluid Tank capability for beyond tier mechanical[default:1024000]
		# Default: 1024000
		# Range: > 1
		beyond_fluid_tank_capability = 1024000
		#Processing multiple for beyond tier mechanical[default:256]
		# Default: 256
		# Range: > 1
		beyond_processing_multiple = 256
		#Processing multiple for beyond tier Deployer[default:32]
		# Default: 32
		# Range: 1 ~ 64
		beyond_deployer_processing_multiple = 32
		#Generated Speed for beyond tier Steam Engine[default:128]
		# Default: 128
		# Range: 1 ~ 256
		beyond_steam_engine_generated_speed = 128
		#Capacity for beyond tier Steam Engine[default:16384.0]
		# Default: 16384.0
		# Range: 1.0 ~ 2.147483647E9
		beyond_steam_engine_capacity = 16384.0
		#Impact needed for beyond tier mechanical press[default:2048.0]
		# Default: 2048.0
		# Range: 1.0 ~ 1.7976931348623157E308
		beyond_mechanical_press_impact = 2048.0
		#Impact needed for beyond tier mechanical mixer[default:1024.0]
		# Default: 1024.0
		# Range: 1.0 ~ 1.7976931348623157E308
		beyond_mechanical_mixer_impact = 1024.0
		#Impact needed forbeyond tier deployer[default:128.0]
		# Default: 128.0
		# Range: 1.0 ~ 1.7976931348623157E308
		beyonddeployer_impact = 128.0
		#Impact needed for beyond tier saw[default:512.0]
		# Default: 512.0
		# Range: 1.0 ~ 1.7976931348623157E308
		beyond_saw_impact = 512.0
		#Inventory size for beyond tier saw[default:512]
		# Default: 512
		# Range: 4 ~ 4096
		beyond_saw_inventory_size = 512

	[TierSettings.CreativeTier]
		#Item capability for creative tier mechanical[default:2147483647]
		# Default: 2147483647
		# Range: > 1
		creative_item_capability = 2147483647
		#Fluid capability for creative tier mechanical[default:2147483647]
		# Default: 2147483647
		# Range: > 1
		creative_fluid_capability = 2147483647
		#Fluid Tank capability for creative tier mechanical[default:2147483647]
		# Default: 2147483647
		# Range: > 1
		creative_fluid_tank_capability = 2147483647
		#Processing multiple for creative tier mechanical[default:2147483647]
		# Default: 2147483647
		# Range: > 1
		creative_processing_multiple = 2147483647
		#Processing multiple for creative tier Deployer[default:64]
		# Default: 64
		# Range: 1 ~ 64
		creative_deployer_processing_multiple = 64
		#Generated Speed for creative tier Steam Engine[default:256]
		# Default: 256
		# Range: 1 ~ 256
		creative_steam_engine_generated_speed = 256
		#Capacity for creative tier Steam Engine[default:2.147483647E9]
		# Default: 2.147483647E9
		# Range: 1.0 ~ 2.147483647E9
		creative_steam_engine_capacity = 2.147483647E9
		#Impact needed for creative tier mechanical press[default:8.0]
		# Default: 8.0
		# Range: 1.0 ~ 1.7976931348623157E308
		creative_mechanical_press_impact = 8.0
		#Impact needed for creative tier mechanical mixer[default:4.0]
		# Default: 4.0
		# Range: 1.0 ~ 1.7976931348623157E308
		creative_mechanical_mixer_impact = 4.0
		#Impact needed forcreative tier deployer[default:4.0]
		# Default: 4.0
		# Range: 1.0 ~ 1.7976931348623157E308
		creativedeployer_impact = 4.0
		#Impact needed for creative tier saw[default:8.0]
		# Default: 8.0
		# Range: 1.0 ~ 1.7976931348623157E308
		creative_saw_impact = 8.0
		#Inventory size for creative tier saw[default:4096]
		# Default: 4096
		# Range: 4 ~ 4096
		creative_saw_inventory_size = 4096
