#.
#Packmakers' control panel for internal recipe compat
[recipes]

	#.
	#.
	#Recipes configs
	[recipes.recipes]

		#.
		#Vibrating Table settings
		[recipes.recipes.vibratingTable]
			#.
			#Allows vibrating leaves on vibrating table to get matching drops.
			allowVibratingLeaves = true

		#.
		#Helve Hammer settings
		[recipes.recipes.helveHammer]
			#.
			#Allows processing templateless recipes for Helve Hammer
			allowTemplatelessRecipes = true
			#.
			#Helve Hammer will damage Anvil after finishing recipe
			damageAnvilAfterHammeringRecipe = false
			#.
			#Chance of Anvil damaging after finishing recipe
			# Default: 12
			# Range: 1 ~ 100
			chanceToDamageAnvilAfterHammeringRecipe = 12

#.
#Parameters and abilities of kinetic mechanisms
[kinetics]

		#.
		#.
		#Fine tune the kinetic stats of individual components
		[kinetics.stressValues.v2]

			#.
			#.
			#[in Stress Units]
			#Configure the individual stress impact of mechanical blocks. Note that this cost is doubled for every speed increase it receives.
			[kinetics.stressValues.v2.impact]
				curving_press = 8.0
				vibrating_table = 2.0
				belt_grinder = 4.0
				lathe = 2.0
				helve_kinetic = 8.0
				vacuum_chamber = 4.0
				lathe_moving = 4.0
				spring_coiling_machine = 4.0
				laser = 2.0
				centrifuge = 8.0
