#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Aug 20 20:49:54 MSK 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=2
shaderPack=Sildur's Vibrant Shaders v2.01 Extreme.zip
