#Truly Dark properties file
#Sun Jun 07 15:39:10 SAMT 2026
biome_blacklist=
cloud_darkness=0.1
dark_default=true
dark_end=true
dark_end_fog=0.0
dark_moon=true
dark_nether=true
dark_nether_fog=0.5
dark_overworld=true
dark_sky=true
dark_skyless=true
entity_light_floor=0.05
fog_darkness=0.1
hard_lock=false
ignore_moon_phase=true
moon_phase_intensity=0.45
only_affect_block_light=false
pack_configured=false
require_client_mod=false
setup_version=Manual
sky_darkness=0.5
sky_merge=true
